version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres_data/init:/docker-entrypoint-initdb.d
      - ./postgres_data/volume_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks: 
      - cluster
  rest_app:
    build: ./app
    image: rest_app
    container_name: rest_app
    ports: 
     - 80:8080
    depends_on: 
     - postgres
    restart: always
    networks: 
     - cluster

networks:
  cluster:
    driver: bridge
    